# Generated by Django 2.1.7 on 2019-03-27 08:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('image_name', models.CharField(max_length=100)),
                ('short_description', models.TextField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('level', models.IntegerField(choices=[(1, 'NEWBIE'), (2, 'BEGINNER'), (3, 'INTERMEDIATE'), (4, 'HARD'), (5, 'MASTER')])),
                ('experience_points', models.PositiveIntegerField()),
                ('likes', models.SmallIntegerField(default=0)),
                ('dislikes', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.IntegerField()),
                ('user_input', models.CharField(max_length=255)),
                ('expected_output', models.CharField(max_length=255)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='tags',
            field=models.ManyToManyField(to='exercise.Tag'),
        ),
    ]
