# Generated by Django 2.1.7 on 2019-03-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20190327_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='tags',
            field=models.ManyToManyField(to='exercise.Tag'),
        ),
    ]
