language: python
services:
- postgresql
python:
- 3.6
env:
- DJANGO=2.1 DB=postgres
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database code_simple;' -U postgres
script:
- python manage.py makemigrations
- python manage.py migrate
- python manage.py test && flake8
notifications:
  email:
    recipients:
      - random@email.com
    on_success: never
    on_failure: always
