language: python
services:
- postgresql
python:
- 3.6
env:
- DJANGO=2.1.7 DB=postgres
before_install:
- export DJANGO_SETTINGS_MODULE=ledenbestand.settings.local
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database code_simple;' -U postgres
- python manage.py makemigrations
- python manage.py migrate
script:
- python manage.py test && flake8
notifications:
  email:
    recipients:
      - random@email.com
    on_success: never
    on_failure: always
